coverage:
  status:
    project:
      src:
        informational: true
        paths: ["src/**/*", "!src/test/**/*"]
    patch:
      src:
        informational: true
        paths: ["src/**/*", "!src/test/**/*"]
