comment:
  layout: "header, components"

component_management:
  default_rules:
    statuses:
      - type: project
        informational: true
      - type: patch
        informational: true

  individual_components:
    - component_id: app
      paths: ["src/app**"]
    - component_id: ghosttext
      paths: ["src/ghosttext**"]
    - component_id: infra
      paths: ["src/**", "!src/app**", "!src/ghosttext**", "!src/test/**", "!src/util/**"]
