# This file contains translations for various messages Ghostbird shows.
# The format is as follows:
#
# [<message_id>]
# <language> = "<translated message>"
#
# See https://pontoon.mozilla.org/projects/thunderbirdnet/ for translations for common terms like "email".

[manifest_name]
# Full name of the extension.
en = "Ghostbird - GhostText for Thunderbird"
ja = "Ghostbird - Thunderbird用GhostText"

[manifest_description]
# Description of the extension.
en = "Use your favorite text editor to compose emails"
ja = "好きなテキストエディタでメールを編集"

[manifest_commands_start_ghostbird_description]
# Description of the shortcut key to start Ghostbird.
en = "Connect to the text editor"
ja = "テキストエディタに接続"

[manifest_commands_stop_ghostbird_description]
# Description of the shortcut key to stop Ghostbird.
en = "Disconnect from the text editor"
ja = "テキストエディタから切断"

[manifest_commands_toggle_ghostbird_description]
# Description of the shortcut key to toggle Ghostbird.
en = "Toggle connection with the text editor"
ja = "テキストエディタとの接続を切り替え"

[options_server_port]
en = "GhostText destination port"
ja = "GhostText接続先ポート"

[options_enable_notifications]
en = "Show notifications"
ja = "通知を表示する"

[options_saved]
en = "Options saved"
ja = "保存しました"

[options_error]
en = "Error saving options"
ja = "保存に失敗しました"
