name: '🐞 Report a bug'
description: Something is wrong
type: Bug
title: '[Bug]'
body:
  - type: textarea
    attributes:
      label: Please describe steps to reproduce the problem.
      value: |
        1. Start <kbd>+ New Message</kbd> and press the Ghostbird button...
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the expected behavior after the steps above?
      value: "* The text editor should show[...]"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did happen instead?
      value: "* An error occurs[...]"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: dropdown
    attributes:
      label: OS
      multiple: false
      options:
        - N/A
        - Windows
        - macOS
        - Linux
        - Other / Multiple
    validations:
      required: true

  - type: input
    attributes:
      label: Thunderbird version
    validations:
      required: false

  - type: input
    attributes:
      label: Ghostbird version
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else to add?
