name: ':bug: Report a bug'
description: Is something wrong?
type: Bug
title: '[BUG] '
body:
  - type: textarea
    attributes:
      label: Please describe steps to reproduce the problem.
      value: |
        1. Start <kbd>+ New Message</kbd> and press the Ghostbird button...
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the expected behavior after steps above?
      value: "* The text editor shows..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did happen instead?
      value: "* An error occurs..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: dropdown
    attributes:
      label: OS
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - Other / Multiple / Not relevant
    validations:
      required: true

  - type: input
    attributes:
      label: Thunderbird version
    validations:
      required: true

  - type: input
    attributes:
      label: Ghostbird version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else to add?
