name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: npm

    - name: Enable corepack
      run: corepack enable

    - name: Install Yarn
      run: corepack install

    - name: Get Yarn cache folder
      id: yarn-cache-dir
      run: echo "cache-dir=$(corepack yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore Yarn cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir.outputs.cache-dir }}
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      run: corepack yarn install --immutable

    - name: Build
      run: corepack yarn build

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.xpi
        generate_release_notes: true
